services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pi4b
      - POSTGRES_DB=house-plant-hub
  api:
    container_name: house-plant-hub-api
    environment:
      - ORIGIN=${ORIGIN:-localhost}
      - DB_NAME=house-plant-hub
      - USER=pi4b
      - PASSWORD=password
      - HOST=${ORIGIN:-localhost}
    build: .
    ports:
      - 8000:8000
