# Generated by Django 4.1.13 on 2025-05-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_plant_hub_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.CharField(max_length=150, null=True, verbose_name='Plant Image URL'),
        ),
    ]
