# Generated by Django 4.1.13 on 2025-04-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_plant_hub_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moisturereading',
            old_name='plant_id',
            new_name='plant',
        ),
    ]
