# Generated by Django 4.1.13 on 2025-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_plant_hub_backend', '0003_remove_moisturereading_battery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.CharField(max_length=250, null=True, verbose_name='Plant Image URL'),
        ),
    ]
