name: Containerise and run API code
on:
  push:
    branches:
      - main

jobs:
  api:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: COMPOSE_BAKE=true docker compose build
      - name: Run container
        run: ORIGIN=${{ secrets.SECRET_KEY }} docker compose up -d
