name: Containerise and run API code
on:
  push:
    branches:
      - feat/runner-test

jobs:
  api-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test command
        run: COMPOSE_BAKE=true docker compose build
