name: Containerise and run API code
on:
  push:
    branches:
      - feat/runner-test

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: COMPOSE_BAKE=true docker compose build
      - name: Run image
        run: ORIGIN=houseplant-hub.glen-sharp.uk docker compose up -d
