name: Containerise and run API code
on:
  push:
    branches:
      - feat/runner-test

jobs:
  api-build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "$(ls)"
    # - name: Build docker image
    #   run: COMPOSE_BAKE=true docker compose build
    # - name: Run docker image
    #   run: ORIGIN=houseplant-hub.glen-sharp.uk docker compose up -d
