name: Containerise and run API code
on:
  push:
    branches: [ "feat/runner-test" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: test
        run: ls
    # - name: Build docker image
    #   run: COMPOSE_BAKE=true docker compose build
    # - name: Run docker image
    #   run: ORIGIN=houseplant-hub.glen-sharp.uk docker compose up -d
