name: Containerise and run API code
on:
  push:
    branches:
      - main

jobs:
  api:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: COMPOSE_BAKE=true docker compose build
      - name: Run container
        run: SECRET_KEY=django-insecure-e-4=l#5htfn85e%)cl2g17zh&d&8hpgg4n30c_k8vawyu@abg5 docker compose up -d
