name: Containerise and run API code
on:
  push:
    branches:
      - main

jobs:
  api:
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: COMPOSE_BAKE=true docker compose build
      - name: Run container
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: SECRET_KEY=$SECRET_KEY docker compose up -d
