name: Containerise and run API code
on:
  push:
    branches: [ "main" ]

jobs:
  buld:
    runs-on: self-hosted
    steps:
    - name: Build docker image
      run: COMPOSE_BAKE=true docker compose build
    - name: Run docker image
      run: ORIGIN=houseplant-hub.glen-sharp.uk docker compose up -d
